// Dados extraídos fielmente da planilha 'Folha_de_cálculo_sem_nome.xlsx'
// Fonte oficial: abas mensais (Mai a Dez 2026) do CONTROLE DE PRODUÇÃO — JESIEL E TONIATI 2026
// Nenhum valor foi alterado. Apenas os INSUMOS de cada fórmula são armazenados aqui;
// os resultados (ganho do dia, líquido, totais de quinzena, resumo anual) são recalculados
// em tempo real por lib/calculations.ts, replicando exatamente as fórmulas da planilha.

export type TaxaRef = 'mensal' | 'q1' | 'q2';
export type QuinzenaGroup = 'q1' | 'q2';

export interface DiaProducao {
  num: number;
  data: string; // dd/Mmm/yyyy, como na planilha
  dia: string; // abreviação do dia da semana (Seg, Ter, ...)
  arquivos: number;
  obs: string | null;
  trabalhou: boolean;
  viajou: boolean;
  desconto: number;
  quinzenaGroup: QuinzenaGroup;
  taxaRef: TaxaRef;
  extraFlag?: boolean;   // era 1 (Mai-Jul): 'SERVIÇO EXTRA?' Sim/Não, valor fixo
  valorExtraRaw?: number; // era 2 (Ago-Dez): valor extra lançado diretamente
}

export interface MesProducao {
  sheet: string;
  nome: string;
  slug: string;
  ano: number;
  era: 1 | 2;
  salario: number;
  quinzena1: number;
  quinzena2: number;
  valorExtraFixo: number | null;
  q1Divisor: number;
  q2Divisor: number;
  days: DiaProducao[];
}

export const MESES: MesProducao[] = [
  {
    sheet: "Mai 2026",
    nome: "Maio",
    slug: "maio",
    ano: 2026,
    era: 1,
    salario: 645.0,
    quinzena1: 270.0,
    quinzena2: 375.0,
    valorExtraFixo: 55.0,
    q1Divisor: 11,
    q2Divisor: 10,
    days: [
      { num: 1, data: "28/Abr/2026", dia: "Ter", arquivos: 4.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "mensal", extraFlag: false, },
      { num: 2, data: "29/Abr/2026", dia: "Qua", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "mensal", extraFlag: false, },
      { num: 3, data: "30/Abr/2026", dia: "Qui", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "mensal", extraFlag: false, },
      { num: 4, data: "01/Mai/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 5, data: "04/Mai/2026", dia: "Seg", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: true, },
      { num: 6, data: "05/Mai/2026", dia: "Ter", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 7, data: "06/Mai/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 8, data: "07/Mai/2026", dia: "Qui", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 9, data: "08/Mai/2026", dia: "Sex", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 10, data: "11/Mai/2026", dia: "Seg", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 11, data: "12/Mai/2026", dia: "Ter", arquivos: 4.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 12, data: "13/Mai/2026", dia: "Qua", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 13, data: "14/Mai/2026", dia: "Qui", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 14, data: "15/Mai/2026", dia: "Sex", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 15, data: "18/Mai/2026", dia: "Seg", arquivos: 3.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 16, data: "19/Mai/2026", dia: "Ter", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 17, data: "20/Mai/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 18, data: "21/Mai/2026", dia: "Qui", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 19, data: "22/Mai/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 20, data: "25/Mai/2026", dia: "Seg", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 21, data: "26/Mai/2026", dia: "Ter", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 22, data: "27/Mai/2026", dia: "Qua", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 23, data: "28/Mai/2026", dia: "Qui", arquivos: 3.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 24, data: "29/Mai/2026", dia: "Sex", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
    ],
  },
  {
    sheet: "Jun 2026",
    nome: "Junho",
    slug: "junho",
    ano: 2026,
    era: 1,
    salario: 750.0,
    quinzena1: 375.0,
    quinzena2: 375.0,
    valorExtraFixo: 160.0,
    q1Divisor: 11,
    q2Divisor: 11,
    days: [
      { num: 1, data: "01/Jun/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 2, data: "02/Jun/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 3, data: "03/Jun/2026", dia: "Qua", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 4, data: "04/Jun/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 5, data: "05/Jun/2026", dia: "Sex", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 6, data: "08/Jun/2026", dia: "Seg", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 7, data: "09/Jun/2026", dia: "Ter", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 8, data: "10/Jun/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 9, data: "11/Jun/2026", dia: "Qui", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 10, data: "12/Jun/2026", dia: "Sex", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 11, data: "15/Jun/2026", dia: "Seg", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 12, data: "16/Jun/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 13, data: "17/Jun/2026", dia: "Qua", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 14, data: "18/Jun/2026", dia: "Qui", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 15, data: "19/Jun/2026", dia: "Sex", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 16, data: "22/Jun/2026", dia: "Seg", arquivos: 0, obs: "Serviço Extra - Ao longo do Mês - R$ 320,00 - 50/50 - Edição de vídeos", trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: true, },
      { num: 17, data: "23/Jun/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 18, data: "24/Jun/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 19, data: "25/Jun/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 20, data: "26/Jun/2026", dia: "Sex", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 21, data: "29/Jun/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 22, data: "30/Jun/2026", dia: "Ter", arquivos: 4.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
    ],
  },
  {
    sheet: "Jul 2026",
    nome: "Julho",
    slug: "julho",
    ano: 2026,
    era: 1,
    salario: 750.0,
    quinzena1: 375.0,
    quinzena2: 375.0,
    valorExtraFixo: 0.0,
    q1Divisor: 11,
    q2Divisor: 12,
    days: [
      { num: 1, data: "01/Jul/2026", dia: "Qua", arquivos: 3.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 2, data: "02/Jul/2026", dia: "Qui", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 3, data: "03/Jul/2026", dia: "Sex", arquivos: 3.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 4, data: "06/Jul/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 5, data: "07/Jul/2026", dia: "Ter", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 6, data: "08/Jul/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: true, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 7, data: "09/Jul/2026", dia: "Qui", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 8, data: "10/Jul/2026", dia: "Sex", arquivos: 5.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 9, data: "13/Jul/2026", dia: "Seg", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 10, data: "14/Jul/2026", dia: "Ter", arquivos: 3.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 11, data: "15/Jul/2026", dia: "Qua", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", extraFlag: false, },
      { num: 12, data: "16/Jul/2026", dia: "Qui", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 13, data: "17/Jul/2026", dia: "Sex", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 14, data: "20/Jul/2026", dia: "Seg", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 15, data: "21/Jul/2026", dia: "Ter", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 16, data: "22/Jul/2026", dia: "Qua", arquivos: 1.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 17, data: "23/Jul/2026", dia: "Qui", arquivos: 4.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 18, data: "24/Jul/2026", dia: "Sex", arquivos: 3.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 19, data: "27/Jul/2026", dia: "Seg", arquivos: 2.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 20, data: "28/Jul/2026", dia: "Ter", arquivos: 5.0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 21, data: "29/Jul/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 22, data: "30/Jul/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
      { num: 23, data: "31/Jul/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", extraFlag: false, },
    ],
  },
  {
    sheet: "Ago 2026",
    nome: "Agosto",
    slug: "agosto",
    ano: 2026,
    era: 2,
    salario: 1000.0,
    quinzena1: 500,
    quinzena2: 500,
    valorExtraFixo: null,
    q1Divisor: 10,
    q2Divisor: 11,
    days: [
      { num: 1, data: "03/Ago/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 2, data: "04/Ago/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 3, data: "05/Ago/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 4, data: "06/Ago/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: true, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 5, data: "07/Ago/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: true, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 6, data: "10/Ago/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 7, data: "11/Ago/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 8, data: "12/Ago/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 9, data: "13/Ago/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 10, data: "14/Ago/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 11, data: "17/Ago/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 12, data: "18/Ago/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 13, data: "19/Ago/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 14, data: "20/Ago/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 15, data: "21/Ago/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 16, data: "24/Ago/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 17, data: "25/Ago/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 18, data: "26/Ago/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 19, data: "27/Ago/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 20, data: "28/Ago/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 21, data: "31/Ago/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
    ],
  },
  {
    sheet: "Set 2026",
    nome: "Setembro",
    slug: "setembro",
    ano: 2026,
    era: 2,
    salario: 1000.0,
    quinzena1: 500,
    quinzena2: 500,
    valorExtraFixo: null,
    q1Divisor: 11,
    q2Divisor: 11,
    days: [
      { num: 1, data: "01/Set/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 2, data: "02/Set/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 3, data: "03/Set/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 4, data: "04/Set/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 5, data: "07/Set/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 6, data: "08/Set/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 7, data: "09/Set/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 8, data: "10/Set/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 9, data: "11/Set/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 10, data: "14/Set/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 11, data: "15/Set/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 12, data: "16/Set/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 13, data: "17/Set/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 14, data: "18/Set/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 15, data: "21/Set/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 16, data: "22/Set/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 17, data: "23/Set/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 18, data: "24/Set/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 19, data: "25/Set/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 20, data: "28/Set/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 21, data: "29/Set/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 22, data: "30/Set/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
    ],
  },
  {
    sheet: "Out 2026",
    nome: "Outubro",
    slug: "outubro",
    ano: 2026,
    era: 2,
    salario: 1000.0,
    quinzena1: 500,
    quinzena2: 500,
    valorExtraFixo: null,
    q1Divisor: 11,
    q2Divisor: 11,
    days: [
      { num: 1, data: "01/Out/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 2, data: "02/Out/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 3, data: "05/Out/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 4, data: "06/Out/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 5, data: "07/Out/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 6, data: "08/Out/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 7, data: "09/Out/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 8, data: "12/Out/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 9, data: "13/Out/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 10, data: "14/Out/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 11, data: "15/Out/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 12, data: "16/Out/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 13, data: "19/Out/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 14, data: "20/Out/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 15, data: "21/Out/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 16, data: "22/Out/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 17, data: "23/Out/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 18, data: "26/Out/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 19, data: "27/Out/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 20, data: "28/Out/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 21, data: "29/Out/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 22, data: "30/Out/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
    ],
  },
  {
    sheet: "Nov 2026",
    nome: "Novembro",
    slug: "novembro",
    ano: 2026,
    era: 2,
    salario: 1000.0,
    quinzena1: 500,
    quinzena2: 500,
    valorExtraFixo: null,
    q1Divisor: 10,
    q2Divisor: 11,
    days: [
      { num: 1, data: "02/Nov/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 2, data: "03/Nov/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 3, data: "04/Nov/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 4, data: "05/Nov/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 5, data: "06/Nov/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 6, data: "09/Nov/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 7, data: "10/Nov/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 8, data: "11/Nov/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 9, data: "12/Nov/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 10, data: "13/Nov/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 11, data: "16/Nov/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 12, data: "17/Nov/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 13, data: "18/Nov/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 14, data: "19/Nov/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 15, data: "20/Nov/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 16, data: "23/Nov/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 17, data: "24/Nov/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 18, data: "25/Nov/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 19, data: "26/Nov/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 20, data: "27/Nov/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 21, data: "30/Nov/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
    ],
  },
  {
    sheet: "Dez 2026",
    nome: "Dezembro",
    slug: "dezembro",
    ano: 2026,
    era: 2,
    salario: 1000.0,
    quinzena1: 500,
    quinzena2: 500,
    valorExtraFixo: null,
    q1Divisor: 11,
    q2Divisor: 12,
    days: [
      { num: 1, data: "01/Dez/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 2, data: "02/Dez/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 3, data: "03/Dez/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 4, data: "04/Dez/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 5, data: "07/Dez/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 6, data: "08/Dez/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 7, data: "09/Dez/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 8, data: "10/Dez/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 9, data: "11/Dez/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 10, data: "14/Dez/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 11, data: "15/Dez/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q1", taxaRef: "q1", valorExtraRaw: 0, },
      { num: 12, data: "16/Dez/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 13, data: "17/Dez/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 14, data: "18/Dez/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 15, data: "21/Dez/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 16, data: "22/Dez/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 17, data: "23/Dez/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 18, data: "24/Dez/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 19, data: "25/Dez/2026", dia: "Sex", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 20, data: "28/Dez/2026", dia: "Seg", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 21, data: "29/Dez/2026", dia: "Ter", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 22, data: "30/Dez/2026", dia: "Qua", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
      { num: 23, data: "31/Dez/2026", dia: "Qui", arquivos: 0, obs: null, trabalhou: true, viajou: false, desconto: 0, quinzenaGroup: "q2", taxaRef: "q2", valorExtraRaw: 0, },
    ],
  },
];